spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/correctiontpspring
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/db.changelog-master.xml
    enabled: true
logging:
  level:
    liquibase: INFO
    fr.benseddik.correctiontpspring: DEBUG